import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "~/styles/globals.css";
import { Cinzel, Inter } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import { createTheme, MantineProvider } from "@mantine/core";
import { navigationLinks } from "~/utils/constants";

const theme = createTheme({
  /** Put your mantine theme override here */
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const cinzel = Cinzel({
  subsets: ["latin"],
  variable: "--font-cinzel",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} ${cinzel.variable}`}>
        <TRPCReactProvider>
          <MantineProvider theme={theme}>
            <header>
              <nav className="bg-blue-500 px-8 py-4">
                <ul className="flex gap-6 text-2xl font-medium text-white">
                  {Object.values(navigationLinks).map(
                    ({ icon, link, name }) => {
                      return (
                        <li key={link}>
                          <a href={link} className="flex items-center gap-1">
                            {name} {icon}
                          </a>
                        </li>
                      );
                    },
                  )}
                </ul>
              </nav>
            </header>
            <main className="p-4">{children}</main>
          </MantineProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
